// Regenerate `src/generated/api.ts` from the API's own OpenAPI document.
//
// The SDK's request and response types are derived from this file, so the
// client cannot drift from what the routes actually validate. Run it against a
// running API (`BRIDGE_API`, default http://localhost:3001) after any route or
// schema change and commit the result.
import { writeFileSync } from 'node:fs';
import openapiTS, { astToString } from 'openapi-typescript';

const API = process.env.BRIDGE_API ?? 'http://localhost:3001';
const spec = await (await fetch(`${API}/v1/openapi.json`)).json();

// The ops lane is authenticated by OPS_TOKEN and is not part of the public client.
for (const path of Object.keys(spec.paths)) if (path.startsWith('/ops')) delete spec.paths[path];

const ast = await openapiTS(spec, { alphabetize: true });
const header = `// Generated by scripts/generate-types.mjs from ${API}/v1/openapi.json. Do not edit.\n`;
writeFileSync(new URL('../src/generated/api.ts', import.meta.url), header + astToString(ast));
console.log(`wrote src/generated/api.ts: ${Object.keys(spec.paths).length} paths`);
